import jax.numpy as jnp

def integrate(x, y):
    #integrate y(x) over x
    return jnp.trapz(y, x)

def sigmoid(x, c=1.):
    return 1./(1.+jnp.exp(-c*x))

def relu(x, c=1.):
    return jnp.minimum(1., jnp.maximum(0., c*x))

def dot_product(v1, v2):
    return jnp.sum(jnp.conjugate(v1) * v2, -1)

# generated by ChatGPT
def cofactor(matrix, i, j):
    # Compute the cofactor of element (i, j)
    minor = jnp.delete(jnp.delete(matrix, i, axis=0), j, axis=1)  # Minor matrix after removing i-th row and j-th column
    sign = (-1) ** (i + j)  # Sign of the cofactor
    return sign * jnp.linalg.det(minor)  # Cofactor is sign * determinant of the minor

# generated by ChatGPT
def adjugate(matrix):
    n = matrix.shape[0]
    cofactor_matrix = jnp.array([[cofactor(matrix, i, j) for j in range(n)] for i in range(n)])
    return jnp.transpose(cofactor_matrix)  # Adjugate is the transpose of the cofactor matrix
